[package]
name = "f1s-lib"
version = "0.2.2"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.5", features = ["blocking"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["serde_derive"] }
chrono = "0.4"
